[package]
name = "font-display"
version = "1.0.0"
authors = [""]

[lib]
crate-type = ["cdylib"]

[dependencies]
dbsdk-rs = "0.1.10"
lazy_static = "1.4.0"
rusttype = { version = "0.9.2", features = [ "gpu_cache" ] }
