[package]
name = "dbsdk-rs"
version = "0.1.0"
edition = "2021"
authors = [ "Hazel Stagner" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
field-offset = "0.3.4"
bitmask = "0.5.0"
chrono = "0.4.22"